### ISSUE TITLE
Padronização do nome

### ISSUE THREAD

**Issue by filipebraida** [ATISLabs/SyntheticDatasets.jl#22]
Eu tinha colocado outro nome na primeira versão, pois precisava para não entrar em conflito com a variável do Python. Porém eu mudei isso umas versões atrás. Acho que seria uma boa exportar as funções e colocar o mesmo nome da lib do scikit. O que acha?

@Conradox @nickolasrm @yaansz @Sergiorezende22

**Comment by Conradox** [comment]
Eu acho que poderia ficar do jeito que está, como se fosse a assinatura padrão da nossa library.
