### ISSUE TITLE
Criação de uma seção com um exemplo de plot

### ISSUE THREAD

**Issue by filipebraida** [ATISLabs/SyntheticDatasets.jl#36]
Criação de uma seção no README.md com um subplot (2x2) com 4 plots de funções (mais interessantes). Adicionar o código também no readme para fazer isso.

**Comment by nicolasmagalhaes** [comment]
![image](https://user-images.githubusercontent.com/67385515/94047811-03023c80-fda9-11ea-80fa-4bfb6b5502aa.png)
ficou boa a escolha?
 
E como exatamente é pra ficar no readme?

**Comment by filipebraida** [comment]
Pode criar dps da seção **Installation** a seção **Exemplo**. No mesmo nível de hierarquia.

Nela você pode começar falando que abaixo um exemplo, a imagem e o código.

**Comment by filipebraida** [comment]
pode adicionar o código na pasta examples tb e a imagem com o meu nome do arquivo. Com isso, você pode referenciar a imagem no readme.

**Comment by filipebraida** [comment]
ou até assim:

https://github.com/JuliaEarth/GeoStats.jl/blob/master/README.md

como tutoriais e colocar até o pluto que vc fez lá.
